vim.keymap.set("n", "<leader>lf", vim.lsp.buf.format)
vim.keymap.set("n", "<leader>ff", ":Pick files<CR>")
vim.keymap.set("n", "<leader>fh", ":Pick help<CR>")
vim.keymap.set("n", "-", "<CMD>Oil<CR>", { desc = "Open parent directory" })
vim.keymap.set("n", "<leader>Cr", "<cmd>Compile <cr>", { desc = "compile (prompt)" })
vim.keymap.set("n", "<leader>Cl", "<cmd>Compile last<cr>", { desc = "compile last command" })
vim.keymap.set("n", "<leader>Ce", "<cmd>Compile with-env<cr>", { desc = "compile with env" })
vim.keymap.set("n", "<S-L>", ":bnext<CR>")
vim.keymap.set("n", "<S-H>", ":bprevious<CR>")
vim.keymap.set("n", "<leader>la", vim.lsp.buf.code_action, { desc = "LSP code action" })
vim.keymap.set("n", "<leader>ld", vim.lsp.buf.definition, { desc = "Go to definition" })
vim.keymap.set("n", "<leader>lD", vim.lsp.buf.declaration, { desc = "Go to declaration" })
vim.keymap.set("n", "<leader>li", vim.lsp.buf.implementation, { desc = "Go to implementation" })
vim.keymap.set("n", "<leader>lR", vim.lsp.buf.rename, { desc = "Rename all occurences" })
vim.keymap.set("n", "<leader>lr", vim.lsp.buf.references, { desc = "Go to references" })
vim.keymap.set("n", "<leader>lt", function()
	local is_enabled = vim.diagnostic.is_enabled()
	vim.diagnostic.enable(not is_enabled)
	vim.notify("Diagnostics " .. (is_enabled and "Disabled" or "Enabled"))
end, { desc = "Toggle LSP Diagnostics" })
vim.keymap.set("n", "<leader>wd", "<C-w>q", { desc = "Quit the window" })
vim.keymap.set("n", "<leader>|", ":vsplit<CR><C-w>l", { desc = "Vertical split and move" })
vim.keymap.set("n", "<leader>w|", ":vsplit<CR><C-w>l", { desc = "Vertical split and move" })
vim.keymap.set("n", "<leader>-", ":split<CR><C-w>j", { desc = "Horizontal split and move" })
vim.keymap.set("n", "<leader>w-", ":split<CR><C-w>j", { desc = "Horizontal split and move" })
vim.keymap.set("n", "<C-M-Up>", ":resize +2<CR>", { desc = "Increase window height" })
vim.keymap.set("n", "<C-M-Down>", ":resize -2<CR>", { desc = "Decrease window height" })
vim.keymap.set("n", "<C-M-Left>", ":vertical resize -2<CR>", { desc = "Decrease window width" })
vim.keymap.set("n", "<C-M-Right>", ":vertical resize +2<CR>", { desc = "Increase window width" })
vim.keymap.set("n", "<leader>bd", ":bdelete<CR>", { desc = "Delete buffer" })
vim.keymap.set("n", "<leader>bD", ":bdelete!<CR>", { desc = "Force delete buffer" })
vim.keymap.set("n", "<leader>ff", ":Telescope find_files<CR>", { desc = "Find files in cwd" })
vim.keymap.set("n", "<leader>fg", ":Telescope live_grep<CR>", { desc = "Find pattern using grep" })
vim.keymap.set("n", "<leader>fc", ":Telescope colorscheme<CR>", { desc = "Change colorscheme" })
vim.keymap.set("n", "<leader>fb", ":Telescope buffers<CR>", { desc = "List open buffers" })
vim.keymap.set("n", "<leader>fh", ":Telescope help_tags<CR>", { desc = "Find help tags" })
vim.keymap.set("n", "<leader>fo", ":Telescope oldfiles<CR>", { desc = "Find recently opened files" })
vim.keymap.set("n", "<leader>fr", ":Telescope diagnostics<CR>", { desc = "Find all diagnostics" })
vim.keymap.set("n", "<leader>fb", ":Telescope buffers<CR>", { desc = "Open buffer navigation" })
