local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>lf", vim.lsp.buf.format)
vim.keymap.set("n", "-", "<CMD>Oil<CR>", { desc = "Open parent directory" })
vim.keymap.set("n", "<leader>cr", "<cmd>Compile <cr>", { desc = "compile (prompt)" })
vim.keymap.set("n", "<leader>cl", "<cmd>Compile last<cr>", { desc = "compile last command" })
vim.keymap.set("n", "<leader>ce", "<cmd>Compile with-env<cr>", { desc = "compile with env" })
vim.keymap.set("n", "<S-L>", ":bnext<CR>")
vim.keymap.set("n", "<S-H>", ":bprevious<CR>")
vim.keymap.set("n", "<leader>la", vim.lsp.buf.code_action, { desc = "LSP code action" })
vim.keymap.set("n", "gd", vim.lsp.buf.definition, { desc = "Go to definition" })
vim.keymap.set("n", "<leader>ld", vim.lsp.buf.definition, { desc = "Go to definition" })
vim.keymap.set("n", "<leader>lD", vim.lsp.buf.declaration, { desc = "Go to declaration" })
vim.keymap.set("n", "<leader>li", vim.lsp.buf.implementation, { desc = "Go to implementation" })
vim.keymap.set("n", "<leader>lR", vim.lsp.buf.rename, { desc = "Rename all occurences" })
vim.keymap.set("n", "<leader>lr", vim.lsp.buf.references, { desc = "Go to references" })
vim.keymap.set("n", "<leader>lt", function()
	local is_enabled = vim.diagnostic.is_enabled()
	vim.diagnostic.enable(not is_enabled)
	vim.notify("Diagnostics " .. (is_enabled and "Disabled" or "Enabled"))
end, { desc = "Toggle LSP Diagnostics" })
vim.keymap.set("n", "<leader>wd", "<C-w>q", { desc = "Quit the window" })
vim.keymap.set("n", "<leader>|", ":vsplit<CR><C-w>l", { desc = "Vertical split and move" })
vim.keymap.set("n", "<leader>w|", ":vsplit<CR><C-w>l", { desc = "Vertical split and move" })
vim.keymap.set("n", "<leader>-", ":split<CR><C-w>j", { desc = "Horizontal split and move" })
vim.keymap.set("n", "<leader>w-", ":split<CR><C-w>j", { desc = "Horizontal split and move" })
vim.keymap.set("n", "<C-M-Up>", ":resize +2<CR>", { desc = "Increase window height" })
vim.keymap.set("n", "<C-M-Down>", ":resize -2<CR>", { desc = "Decrease window height" })
vim.keymap.set("n", "<C-M-Left>", ":vertical resize -2<CR>", { desc = "Decrease window width" })
vim.keymap.set("n", "<C-M-Right>", ":vertical resize +2<CR>", { desc = "Increase window width" })
vim.keymap.set("n", "<leader>bd", ":bdelete<CR>", { desc = "Delete buffer" })
vim.keymap.set("n", "<leader>bD", ":bdelete!<CR>", { desc = "Force delete buffer" })
vim.keymap.set("n", "<leader>ff", builtin.find_files, { desc = "Find files in cwd" })
vim.keymap.set("n", "<leader>fg", builtin.live_grep, { desc = "Find pattern using grep" })
vim.keymap.set("n", "<leader>fc", builtin.colorscheme, { desc = "Change colorscheme" })
vim.keymap.set("n", "<leader>fb", builtin.buffers, { desc = "List open buffers" })
vim.keymap.set("n", "<leader>fh", builtin.help_tags, { desc = "Find help tags" })
vim.keymap.set("n", "<leader>fo", builtin.oldfiles, { desc = "Find recently opened files" })
vim.keymap.set("n", "<leader>fd", builtin.diagnostics, { desc = "Find all diagnostics" })
vim.keymap.set("n", "<leader>fb", builtin.buffers, { desc = "Open buffer navigation" })

-- Minor remap from ThePrimeagen

vim.keymap.set("v", "<M-j>", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "<M-k>", ":m '<-2<CR>gv=gv")
vim.keymap.set("n", "J", "mzJ`z")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "n", "nzzzv")
vim.keymap.set("n", "N", "Nzzzv")

-- greatest remap ever
vim.keymap.set("x", "<leader>p", [["_dP]])
-- next greatest remap ever : asbjornHaland
vim.keymap.set({ "n", "v" }, "<leader>y", [["+y]])
vim.keymap.set("n", "<leader>Y", [["+Y]])

vim.keymap.set({ "n", "v" }, "<leader>d", '"_d')
